[build]
publish = "public"
command = "make build"

[build.environment]
HUGO_VERSION = "0.138.0"

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[[headers]]
  for = "/*/*.*.*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable'''
